#!/usr/bin/env bash
set -e

# source in helper functions
source "$( dirname "${BASH_SOURCE[0]}" )/helpers/helpers.sh"

# Check if required tools are available
ensureMake
ensureForge
ensureDocker

# Build the contracts and dependencies
log "Building AVS performer..."
BUILD_CONTAINER=true ./.hourglass/scripts/build.sh >&2

# Get container info from build.yaml
buildParams=$(cat ../.hourglass/build.yaml)
registry=$(echo "$buildParams" | yq -r '.container.registry')
image=$(echo "$buildParams" | yq -r '.container.image')
tag=$(echo "$buildParams" | yq -r '.container.version')

# Construct full image name
if [[ ! -z "$registry" ]]; then
    full_image="${registry}/${image}:${tag}"
else
    full_image="${image}:${tag}"
fi

# Get the container digest
log "Getting container digest..."
DIGEST=$(docker inspect "$full_image" --format='{{.RepoDigests}}' | cut -d'@' -f2)

# # Update the yaml file with the artifact digest
# yaml_file="config/contexts/0.0.6.yaml"
# if [ -f "$yaml_file" ]; then
#     # Use yq to update the artifacts field
#     yq e ".artifacts = \"$DIGEST\"" -i "$yaml_file"
#     log "Updated artifacts field in $yaml_file with digest: $DIGEST"
# else
#     log "Error: $yaml_file not found"
#     exit 1
# fi

log "Updated artifacts field in file with digest: $DIGEST"

log "Building contracts..."
cd .devkit/contracts && forge clean && forge build -- --include ../../contracts/**/*.sol >&2

log "Build completed successfully."