{{- $values := (datasource "values") -}}
apiVersion: eigenruntime.io/v1
kind: Hourglass
name: {{ $values.project.name }}
version: {{ $values.project.version }}
spec:
  aggregator:
    registry: {{ $values.aggregator.image.registry }}
    digest: {{ $values.aggregator.image.digest }}
    env:
    resources:
      tee_enabled: {{ $values.aggregator.resources.tee_enabled }}