{{- $values := (datasource "values") -}}
apiVersion: eigenruntime.io/v1
kind: Hourglass
name: {{ $values.project.name }}
version: {{ $values.project.version }}
spec:
  executor:
    registry: {{ $values.executor.image.registry }}
    digest: {{ $values.executor.image.digest }}
    command: ["executor", "run"]
    env:
    {{- range $k, $v := $values.executor.env }}
      - name: {{ $k }}
        value: "{{ $v }}"
    {{- end }}
    resources:
      tee_enabled: {{ $values.executor.resources.tee_enabled }}
  performer:
    registry: {{ $values.performer.image.registry }}
    digest: {{ $values.performer.image.digest }}
    command: ["performer", "run"]
    env:
    {{- range $k, $v := $values.performer.env }}
      - name: {{ $k }}
        value: "{{ $v }}"
    {{- end }}
    resources:
      tee_enabled: {{ $values.performer.resources.tee_enabled }}
